apiVersion: v1
kind: Pod
metadata:
  name: tredex-pod
spec:
  containers:
    - name: mongodb
      image: docker.io/library/mongo:latest
      ports:
        - containerPort: 27017
          hostPort: 27017
